import { sectionPaths } from '../../components/layout/AppShell'
import type { AgentModuleManifest } from './types'

/**
 * Fuente unica de verdad de modulos para el agente. Las 14 rutas del
 * sidebar vienen de AppShell.sectionPaths (cero duplicacion). Las 8 rutas
 * restantes son reales pero NO viven en sectionPaths - App.tsx::renderSection
 * las resuelve por chequeo directo de `window.location.pathname` ANTES del
 * switch de SectionId (ver lineas 122-186 de App.tsx). Son literales aca
 * porque extraerlas a un objeto compartido habria significado refactorizar
 * el routing manual de App.tsx, fuera del alcance de esta etapa; si esas
 * rutas cambian, este archivo y App.tsx deben actualizarse juntos (marcado
 * explicitamente para que no se desincronicen en silencio).
 */
const EXTRA_ROUTES = {
  prediccion: '/prediccion',
  simulador: '/simulador',
  comparativa: '/comparativa',
  operatorRanking: '/operator-ranking',
  adminSistema: '/admin/sistema',
  adminUsers: '/admin/users',
  adminDemoAccess: '/admin/demo-access',
  adminAuditoria: '/admin/auditoria',
} as const

const SHIFT_FILTER = { id: 'shift', label: 'Turno', type: 'shift', allowedValues: ['DIA', 'NOCHE', 'AMBOS'] } as const
const DATE_FILTERS = [
  { id: 'start_date', label: 'Fecha desde', type: 'date' } as const,
  { id: 'end_date', label: 'Fecha hasta', type: 'date' } as const,
]
const EQUIPMENT_FILTER = { id: 'equipo', label: 'Equipo', type: 'equipment' } as const

export const NORTHMINE_MODULES: Record<string, AgentModuleManifest> = {
  cockpit: {
    id: 'cockpit',
    route: sectionPaths.cockpit,
    label: 'Decision Cockpit',
    description: 'Costos, riesgo y accion recomendada del turno.',
    category: 'operacional',
    agentAccess: 'read_only',
    minRoles: 'any',
    filters: [SHIFT_FILTER, ...DATE_FILTERS],
    entities: [{ type: 'equipment', label: 'CAEX' }, { type: 'loader', label: 'Pala' }],
    supportedActions: ['navigate', 'set_filter', 'clear_filter', 'focus_widget', 'explain_widget'],
    instrumented: true,
  },
  operationalMap3d: {
    id: 'operationalMap3d',
    route: sectionPaths.operationalMap3d,
    label: 'Mapa Operacional 3D',
    description: 'Constelacion de datos operacionales en 3D.',
    category: 'geoespacial',
    agentAccess: 'read_only',
    minRoles: 'any',
    filters: [],
    entities: [],
    supportedActions: ['navigate'],
    instrumented: false,
  },
  dashboard: {
    id: 'dashboard',
    route: sectionPaths.dashboard,
    label: 'Resumen',
    description: 'Vista ejecutiva general.',
    category: 'operacional',
    agentAccess: 'read_only',
    minRoles: 'any',
    filters: [SHIFT_FILTER, ...DATE_FILTERS],
    entities: [],
    supportedActions: ['navigate', 'set_filter', 'clear_filter'],
    instrumented: false,
  },
  turno: {
    id: 'turno',
    route: sectionPaths.turno,
    label: 'Turno Actual',
    description: 'Operacion en tiempo real del turno.',
    category: 'operacional',
    agentAccess: 'read_only',
    minRoles: 'any',
    filters: [SHIFT_FILTER],
    entities: [{ type: 'equipment', label: 'CAEX' }, { type: 'loader', label: 'Pala' }],
    supportedActions: ['navigate', 'set_filter', 'clear_filter', 'select_entity'],
    instrumented: false,
  },
  produccion: {
    id: 'produccion',
    route: sectionPaths.produccion,
    label: 'Producción',
    description: 'Tonelaje, cumplimiento de plan y tiempo de ciclo por hora.',
    category: 'operacional',
    agentAccess: 'read_only',
    minRoles: 'any',
    filters: [SHIFT_FILTER, ...DATE_FILTERS, EQUIPMENT_FILTER],
    entities: [{ type: 'equipment', label: 'CAEX' }, { type: 'loader', label: 'Pala' }],
    supportedActions: ['navigate', 'set_filter', 'clear_filter', 'select_entity', 'focus_widget', 'explain_widget'],
    instrumented: true,
  },
  rendimiento: {
    id: 'rendimiento',
    route: sectionPaths.rendimiento,
    label: 'Rendimiento',
    description: 'Horas y demoras operacionales.',
    category: 'analitico',
    agentAccess: 'read_only',
    minRoles: 'any',
    filters: [SHIFT_FILTER, ...DATE_FILTERS],
    entities: [],
    supportedActions: ['navigate', 'set_filter', 'clear_filter'],
    instrumented: false,
  },
  flota: {
    id: 'flota',
    route: sectionPaths.flota,
    label: 'Flota',
    description: 'Estado, disponibilidad y utilizacion de CAEX.',
    category: 'operacional',
    agentAccess: 'read_only',
    minRoles: 'any',
    filters: [SHIFT_FILTER, EQUIPMENT_FILTER],
    entities: [{ type: 'equipment', label: 'CAEX' }],
    supportedActions: ['navigate', 'set_filter', 'clear_filter', 'select_entity', 'open_entity', 'focus_widget'],
    instrumented: true,
  },
  carguio: {
    id: 'carguio',
    route: sectionPaths.carguio,
    label: 'Carguío',
    description: 'Palas y frentes activos.',
    category: 'operacional',
    agentAccess: 'read_only',
    minRoles: 'any',
    filters: [SHIFT_FILTER, EQUIPMENT_FILTER],
    entities: [{ type: 'loader', label: 'Pala' }],
    supportedActions: ['navigate', 'set_filter', 'clear_filter', 'select_entity'],
    instrumented: false,
  },
  averias: {
    id: 'averias',
    route: sectionPaths.averias,
    label: 'Averías',
    description: 'Inactividad y fallas de equipos.',
    category: 'operacional',
    agentAccess: 'read_only',
    minRoles: 'any',
    filters: [...DATE_FILTERS, EQUIPMENT_FILTER],
    entities: [{ type: 'equipment', label: 'Equipo' }],
    supportedActions: ['navigate', 'set_filter', 'clear_filter', 'select_entity'],
    instrumented: false,
  },
  analisis: {
    id: 'analisis',
    route: sectionPaths.analisis,
    label: 'Análisis Experto',
    description: 'Produccion cruzada con mantencion.',
    category: 'analitico',
    agentAccess: 'read_only',
    minRoles: 'any',
    filters: [...DATE_FILTERS],
    entities: [],
    supportedActions: ['navigate'],
    instrumented: false,
  },
  aerea: {
    id: 'aerea',
    route: sectionPaths.aerea,
    label: 'Vista Aérea',
    description: 'Ortomosaicos y estado geoespacial.',
    category: 'geoespacial',
    agentAccess: 'read_only',
    minRoles: 'any',
    filters: [],
    entities: [],
    // No hay contrato Leaflet todavia (seccion 13/20): solo navegacion.
    supportedActions: ['navigate'],
    instrumented: false,
  },
  alertas: {
    id: 'alertas',
    route: sectionPaths.alertas,
    label: 'Alertas',
    description: 'Riesgo y seguridad operacional.',
    category: 'operacional',
    agentAccess: 'read_only',
    minRoles: 'any',
    filters: [{ id: 'shift', label: 'Turno', type: 'shift', allowedValues: ['DIA', 'NOCHE', 'AMBOS'] }],
    entities: [{ type: 'alert', label: 'Alerta' }],
    supportedActions: ['navigate', 'select_entity', 'open_entity', 'focus_widget'],
    instrumented: true,
  },
  reportes: {
    id: 'reportes',
    route: sectionPaths.reportes,
    label: 'Reportes',
    description: 'Informes de turno y periodo.',
    category: 'operacional',
    agentAccess: 'read_only',
    minRoles: 'any',
    filters: [...DATE_FILTERS],
    entities: [],
    supportedActions: ['navigate', 'focus_widget'],
    instrumented: true,
  },
  admin: {
    id: 'admin',
    route: sectionPaths.admin,
    label: 'Admin',
    description: 'Marcador de seccion sin contenido real todavia.',
    category: 'administrativo',
    // Placeholder sin funcionalidad real - nunca se afirma control semantico
    // de algo que no existe (seccion 20 del brief).
    agentAccess: 'unavailable',
    minRoles: ['admin'],
    filters: [],
    entities: [],
    supportedActions: [],
    instrumented: false,
  },
  prediccion: {
    id: 'prediccion',
    route: EXTRA_ROUTES.prediccion,
    label: 'Predicción',
    description: 'Proyeccion de produccion con Machine Learning.',
    category: 'predictivo',
    agentAccess: 'read_only',
    minRoles: 'any',
    filters: [],
    entities: [],
    supportedActions: ['navigate'],
    instrumented: false,
  },
  simulador: {
    id: 'simulador',
    route: EXTRA_ROUTES.simulador,
    label: 'Simulador',
    description: 'Simulacion de escenarios de flota.',
    category: 'predictivo',
    agentAccess: 'read_only',
    minRoles: 'any',
    filters: [],
    entities: [],
    // Correr una simulacion escribe un resultado nuevo: no se expone como
    // accion del agente todavia (fuera del tool registry read-only actual).
    supportedActions: ['navigate'],
    instrumented: false,
  },
  comparativa: {
    id: 'comparativa',
    route: EXTRA_ROUTES.comparativa,
    label: 'Comparativa',
    description: 'Dos periodos lado a lado, variacion por KPI.',
    category: 'analitico',
    agentAccess: 'read_only',
    minRoles: 'any',
    filters: [...DATE_FILTERS],
    entities: [],
    supportedActions: ['navigate', 'set_filter', 'clear_filter'],
    instrumented: false,
  },
  operatorRanking: {
    id: 'operatorRanking',
    route: EXTRA_ROUTES.operatorRanking,
    label: 'Operator Ranking',
    description: 'Ranking y scoring de operadores.',
    category: 'analitico',
    agentAccess: 'read_only',
    minRoles: ['admin', 'supervisor'],
    filters: [],
    entities: [],
    supportedActions: ['navigate'],
    instrumented: false,
  },
  adminSistema: {
    id: 'adminSistema',
    route: EXTRA_ROUTES.adminSistema,
    label: 'Sistema',
    description: 'Configuracion de sistema.',
    category: 'administrativo',
    agentAccess: 'unavailable',
    minRoles: ['admin'],
    filters: [],
    entities: [],
    supportedActions: [],
    instrumented: false,
  },
  adminUsers: {
    id: 'adminUsers',
    route: EXTRA_ROUTES.adminUsers,
    label: 'Usuarios',
    description: 'Administracion de usuarios.',
    category: 'administrativo',
    agentAccess: 'unavailable',
    minRoles: ['admin'],
    filters: [],
    entities: [],
    supportedActions: [],
    instrumented: false,
  },
  adminDemoAccess: {
    id: 'adminDemoAccess',
    route: EXTRA_ROUTES.adminDemoAccess,
    label: 'Acceso Demo',
    description: 'Solicitudes de acceso a la demo publica.',
    category: 'administrativo',
    agentAccess: 'unavailable',
    minRoles: ['admin'],
    filters: [],
    entities: [],
    supportedActions: [],
    instrumented: false,
  },
  adminAuditoria: {
    id: 'adminAuditoria',
    route: EXTRA_ROUTES.adminAuditoria,
    label: 'Auditoría',
    description: 'Bitacora de seguridad del sistema.',
    category: 'administrativo',
    // Conservador a proposito: es informacion sensible de seguridad: el
    // agente puede navegar ahi si el rol lo permite, pero no se trata como
    // una fuente de datos operacionales mas.
    agentAccess: 'unavailable',
    minRoles: ['admin'],
    filters: [],
    entities: [],
    supportedActions: [],
    instrumented: false,
  },
}

export function moduleForRoute(pathname: string): AgentModuleManifest | null {
  return Object.values(NORTHMINE_MODULES).find((module) => module.route === pathname) ?? null
}
